### ISSUE TITLE
Why Q-NN does not multiply lr=0.85 like Q-table?

### ISSUE THREAD

**Issue by dino94313** [lukepark327/studying-RL#1]
https://github.com/lukepark327/studying-RL/blob/e286364f4650dc587eeee9f9e6ec3bd03e0ffa50/1-Q-NN/src/agent.py#L87

Actually multiplying 0.85 makes values of Q-table (driven by NN) lower than expectation. Is that a reason why?

**Comment by lukepark327** [comment]
https://towardsdatascience.com/reinforcement-learning-tutorial-part-3-basic-deep-q-learning-186164c3bf4

The lr is no longer needed because of optimizer already has it
